### ISSUE TITLE
transparent colors five overlapping icons instead of simple plus button

### ISSUE THREAD

**Issue by yuraxdrumz** [dwicao/react-native-circle-button#3]
Hey, 
i want to make the button colors transparent, the problem is that it shows all the icons stacked on top of each other instead of just appearing when i click the plus button.

**Comment by dwicao** [comment]
@yuraxdrumz Thanks for reporting the issue, I've fixed it.
Please update package `react-native-circle-button` to the latest version (v1.0.5)
Then you can use transparent into primaryColor and secondaryColor like this:
```jsx
<CircleButton primaryColor="rgba(0, 0, 0, 0.2)" secondaryColor="rgba(0, 0, 0, 0.1)" />
```

**Comment by yuraxdrumz** [comment]
@dwicao Thanks man !
